logging:
  file:
    name: football-su
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 7