server:
  port: 8088
  servlet:
    context-path: /pic
  
spring:
  profiles:
    active: dev
  application:
    name: picture-browser

jwt:
  secret-key: YTV1ZEFUTm0vQUg0QkM3WVNCUTVhbFM0NTJQMllGVlVxbXRZUFhIdmc1OD0=
  expire-time: 7200000


